### ISSUE TITLE
Azure Vintage: Missing image for security isolation layers concept

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/docs#1981]
In the page, an image is missing showing isolation layers concept.

![Screenshot 2023-11-17 at 2 57 24 PM](https://github.com/giantswarm/docs/assets/5674762/d234ae6d-1518-405f-806a-8b8d0cee31da)

**Comment by tuladhar** [comment]
cc: @giantswarm/sig-docs

**Comment by AndiDog** [comment]
I think the architecture diagram is meant there, as rendered by `![Azure management cluster architecture](architecture-azure-control-plane.png)`

**Comment by tuladhar** [comment]
In AWS, this is the diagram used.
![image](https://github.com/giantswarm/docs/assets/5674762/41c64659-789f-4ea9-b9aa-fbc635a1410d)

**Comment by pipo02mix** [comment]
yeah it is that one

**Comment by pipo02mix** [comment]
scratch that, I meant the phrase references the control plane image which is already included but in the section before :)
I have created a [PR](https://github.com/giantswarm/docs/pull/2012) to clarify it
