### ISSUE TITLE
Replace deprecated --tenant-internal flag for gsctl create kubeconfig with --internal-api

### ISSUE THREAD

**Issue by albuch** [giantswarm/docs#840]
[gsctl create kubconfig docs](https://github.com/giantswarm/docs/blob/master/src/content/ui-api/gsctl/create-kubeconfig.md) references deprecated flag for `--tenant-internal`which should be replaced with `--tenant-internal`.

**Comment by marians** [comment]
Fixed in https://github.com/giantswarm/docs/pull/841
